export enum Constants {
  CODE = "CODE",
  NAMES = "NAMES",
  PLUS_ONE = "PLUS_ONE",
  DIETARY_REQUIREMENTS = "DIETARY_REQUIREMENTS",
  ALLERGIES = "ALLERGIES",
  ANSWER = "ANSWER",
  MESSAGE = "MESSAGE",
  ATTENDANCE = "ATTENDANCE",
}
