import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { Ballet, Sora, Crimson_Pro,  MedievalSharp, Almendra, Almendra_Display, Macondo_Swash_Caps, Metamorphous } from "@next/font/google";

// const bf = MedievalSharp({ weight: "400", subsets: ["latin"] });
const bf = Sora({ weight: "400", subsets: ["latin"] });
// const bf = Metamorphous({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bf.className} font-medium text-slate-800 bg-white text-xl max-w-5xl m-auto`}>{children}</body>
    </html>
  );
}
