// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import keyjson from "../../joandjulian-0761ab687054.json";

const client = () =>
  new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: keyjson.client_email, //process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: keyjson.private_key, //process.env.GOOGLE_PRIVATE_KEY,
    scopes: [
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/drive.file",
    ],
  });

const loadSheet = async (serviceAccountAuth: JWT) => {
  const sheet = new GoogleSpreadsheet(
    process.env.GOOGLE_SHEET_ID as string,
    serviceAccountAuth
  );

  await sheet.loadInfo();
  return sheet;
};

export async function GET(req: Request) {
  const serviceAccountAuth = client();
  try {
    // const acccessToken = await serviceAccountAuth.refreshAccessToken()
    // console.log(acccessToken);

    const sheet = await loadSheet(serviceAccountAuth);
    sheet.sheet
    console.log("load info");
    // console.log("loaded info", doc.title);
    return Response.json({ ok: true });
  } catch (err: any) {
    console.error(err);
  }

  return Response.json({ title: "error" });
}

export async function POST(req: Request) {
  console.log("hello");
  const serviceAccountAuth = new JWT({
    email: keyjson.client_email,
    key: keyjson.private_key,
    scopes: [
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/drive.file",
    ],
  });
  try {
    // const acccessToken = await serviceAccountAuth.refreshAccessToken()
    // console.log(acccessToken);

    const doc = new GoogleSpreadsheet(
      process.env.GOOGLE_SHEET_ID as string,
      serviceAccountAuth
    );
    console.log("load info");

    // const json = await serviceAccountAuth.request({
    //   url: `https://sheets.googleapis.com/v4/spreadsheets/${process.env.GOOGLE_SHEET_ID}`,
    // });
    await doc.loadInfo(true);
    console.log(doc.title);
    // console.log("loaded info", doc.title);
    return Response.json({ ok: true });
  } catch (err: any) {
    console.error(err);
  }

  return Response.json({ title: "error" });
}
